### ISSUE TITLE
Set to use 'best' location or specific Country?

### ISSUE THREAD

**Issue by Ltek** [wiorca/docker-windscribe-mono#1]
I'm wondering if there is a way to have the Windscribe client connect to the 'best' location each time and/or only allow it to use a specific country?... vs a single static location?

thx!

**Comment by wiorca** [comment]
Any location string that the windscribe-cli client will accept is what is supported here.  I don't really want to extend client features in the docker container so you can verify with the windscribe folks, or my favorite place:  https://www.reddit.com/r/Windscribe
